### ISSUE TITLE
Low-connecting glyphs get disconnected

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/mehraban-book-pahlavi#1]
From @amirmahdimoslehi 

> I noticed a new joining issue in BP: When two `lam-ar` come after the lower forms. Additionally, when `lam-ar.medi` joins from the left to baseline connecting shapes and then joins to lower connecting shape from the right.

![Screenshot 2023-06-21 at 22 34 33](https://github.com/rosettatype/mehraban-book-pahlavi/assets/485475/7ce6c948-9d9a-48ae-8ad3-ab59f019a35d)

**Comment by amirmahdimoslehi** [comment]
`jeem-ar` connecting issues: When **the lower form shapes** come _before_ **two** `jeem-ar` and when **the lower form** of `jeem-ar` come _after_ a **baseline connecting letter**.
<img width="830" alt="Screenshot 2023-06-22 at 08 47 07" src="https://github.com/rosettatype/mehraban-book-pahlavi/assets/65105713/da3dff9b-8390-450d-9758-4e45fbb74dc1">
